# Generated by Django 6.0.4 on 2026-04-22 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Numer rejestracyjny')),
                ('bus_type', models.CharField(choices=[('standard', 'Standardowy'), ('comfort', 'Komfortowy'), ('luxury', 'Luksusowy')], max_length=20, verbose_name='Typ autobusu')),
                ('total_seats', models.PositiveIntegerField(verbose_name='Liczba miejsc')),
                ('seats_per_row', models.PositiveIntegerField(default=4, verbose_name='Miejsc w rzadzie')),
                ('has_ac', models.BooleanField(default=True, verbose_name='Klimatyzacja')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='WiFi')),
                ('has_toilet', models.BooleanField(default=False, verbose_name='Toaleta')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Autobus',
                'verbose_name_plural': 'Autobusy',
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa trasy')),
                ('departure_city', models.CharField(max_length=100, verbose_name='Miasto wyjazdu')),
                ('arrival_city', models.CharField(max_length=100, verbose_name='Miasto przyjazdu')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Dystans (km)')),
                ('estimated_time', models.DurationField(verbose_name='Szacowany czas podrózy')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena bazowa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trasa',
                'verbose_name_plural': 'Trasy',
                'ordering': ['departure_city', 'arrival_city'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Imie')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena calkowita')),
                ('booking_reference', models.CharField(max_length=50, unique=True, verbose_name='Numer rezerwacji')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Oplacone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uzytkownik')),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota')),
                ('payment_method', models.CharField(choices=[('card', 'Karta kredytowa'), ('bank_transfer', 'Przelew bankowy'), ('cash', 'Gotowka')], max_length=20, verbose_name='Metoda platnosci')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('completed', 'Zakonczone'), ('failed', 'Nieudane'), ('refunded', 'Zwrot')], default='pending', max_length=20, verbose_name='Status platnosci')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID transakcji')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.booking', verbose_name='Rezerwacja')),
            ],
            options={
                'verbose_name': 'Platnosc',
                'verbose_name_plural': 'Platnosci',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='Czas odjazdu')),
                ('arrival_time', models.DateTimeField(verbose_name='Czas przyjazdu')),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Mnoznik ceny')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.bus', verbose_name='Autobus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.route', verbose_name='Trasa')),
            ],
            options={
                'verbose_name': 'Rozklad jazdy',
                'verbose_name_plural': 'Rozklady jazdy',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(verbose_name='Numer miejsca')),
                ('status', models.CharField(choices=[('available', 'Dostepny'), ('booked', 'Zarezerwowany'), ('paid', 'Oplacony'), ('cancelled', 'Anulowany')], default='available', max_length=20, verbose_name='Status')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('booking_reference', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numer rezerwacji')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.schedule', verbose_name='Rozklad')),
            ],
            options={
                'verbose_name': 'Bilet',
                'verbose_name_plural': 'Bilety',
                'ordering': ['schedule', 'seat_number'],
                'unique_together': {('schedule', 'seat_number')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='tickets',
            field=models.ManyToManyField(to='tickets.ticket', verbose_name='Bilety'),
        ),
    ]
