# Generated by Django 6.0.4 on 2026-04-22 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['registration_number'], 'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['departure_city', 'arrival_city'], 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['departure_time'], 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['schedule', 'seat_number'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AddField(
            model_name='route',
            name='arrival_address',
            field=models.CharField(default='Main Bus Station', max_length=200, verbose_name='Arrival address'),
        ),
        migrations.AddField(
            model_name='route',
            name='departure_address',
            field=models.CharField(default='Main Bus Station', max_length=200, verbose_name='Departure address'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='Booking reference'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tickets',
            field=models.ManyToManyField(to='tickets.ticket', verbose_name='Tickets'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total price'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('comfort', 'Comfort'), ('luxury', 'Luxury')], max_length=20, verbose_name='Bus type'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='has_ac',
            field=models.BooleanField(default=True, verbose_name='Air conditioning'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='has_toilet',
            field=models.BooleanField(default=False, verbose_name='Toilet'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='registration_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Registration number'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seats_per_row',
            field=models.PositiveIntegerField(default=4, verbose_name='Seats per row'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='total_seats',
            field=models.PositiveIntegerField(verbose_name='Total seats'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.booking', verbose_name='Booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit card'), ('bank_transfer', 'Bank transfer'), ('cash', 'Cash')], max_length=20, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='route',
            name='arrival_city',
            field=models.CharField(max_length=100, verbose_name='Arrival city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base price'),
        ),
        migrations.AlterField(
            model_name='route',
            name='departure_city',
            field=models.CharField(max_length=100, verbose_name='Departure city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Distance (km)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='estimated_time',
            field=models.DurationField(verbose_name='Estimated travel time'),
        ),
        migrations.AlterField(
            model_name='route',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Route name'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='arrival_time',
            field=models.DateTimeField(verbose_name='Arrival time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.bus', verbose_name='Bus'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='departure_time',
            field=models.DateTimeField(verbose_name='Departure time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='price_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Price multiplier'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.route', verbose_name='Route'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Booking reference'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.schedule', verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.PositiveIntegerField(verbose_name='Seat number'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='available', max_length=20, verbose_name='Status'),
        ),
    ]
