# Generated by Django 6.0.4 on 2026-04-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_booking_options_alter_bus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='departure_date',
            field=models.DateField(blank=True, help_text='Date when this route operates', null=True, verbose_name='Departure date'),
        ),
    ]
