# Generated by Django 6.0.4 on 2026-04-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_route_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit card'), ('bank_transfer', 'Bank transfer'), ('cash', 'Cash'), ('lipay', 'LiPay'), ('paypal', 'PayPal')], max_length=20, verbose_name='Payment method'),
        ),
    ]
