# Generated by Django 6.0.4 on 2026-04-24 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Layout name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('total_seats', models.PositiveIntegerField(verbose_name='Total seats')),
                ('seats_per_row', models.PositiveIntegerField(default=4, verbose_name='Seats per row')),
                ('layout_data', models.JSONField(help_text='2D array representing seat layout', verbose_name='Layout data')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seat Layout',
                'verbose_name_plural': 'Seat Layouts',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='seat_layout_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.seatlayout', verbose_name='Seat layout'),
        ),
    ]
