# Generated by Django 6.0.4 on 2026-04-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_seatlayout_bus_seat_layout_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatlayout',
            name='layout_data',
            field=models.JSONField(blank=True, help_text='2D array representing seat layout', null=True, verbose_name='Layout data'),
        ),
    ]
